language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
services:
- redis-server
before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.2.deb
  && sudo dpkg -i --force-confnew elasticsearch-6.3.2.deb && sudo service elasticsearch
  restart
- mkdir -p ~/logs/dialcode/
- find ${TRAVIS_BUILD_DIR}/ -type f -name "log4j2.xml" -print0 | xargs -0 sed -i -e
  's/\/data\/logs/~\/logs/g'
- find ${TRAVIS_BUILD_DIR}/ -type f -name "logback.xml" -print0 | xargs -0 sed -i
  -e 's/\/data\/logs/logs/g'
- find ${TRAVIS_BUILD_DIR}/ -type f -name "application.conf" -print0 | xargs -0 sed
  -i -e 's/\/data\//~\//g'
- find ${TRAVIS_BUILD_DIR}/ -type f -name "*.java" -print0 | xargs -0 sed -i -e 's/\/data\//~\//g'
- sleep 10
script:
- mvn clean install